INSERT INTO public.users (gender, role, address, city, country, name, password, phone_number, surname, username) VALUES (0, 1, 'Nikole Pasica 3', 'Novi Sad', 'Srbija', 'Nikola', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '0641234567', 'Nikolic', 'nikola@gmail.com');

INSERT INTO public.users (gender, role, address, city, country, jmbg, name, password, phone_number, surname, username) VALUES (1, 0, 'Temerinska 10', 'Novi Sad', 'Srbija', '1006993123654', 'Ana', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '065123789', 'Bogdanovic', 'ana@gmail.com');
INSERT INTO public.users (gender, role, address, city, country, jmbg, name, password, phone_number, surname, username) VALUES (0, 0, 'Janka Cmelika 33', 'Novi Sad', 'Srbija', '2410995456789', 'Stefan', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '065234908', 'Stefanovic', 'stefan@gmail.com');
INSERT INTO public.users (gender, role, address, city, country, jmbg, name, password, phone_number, surname, username) VALUES (1, 0, 'Petra Kocica 11', 'Novi Sad', 'Srbija', '0605983990987', 'Ema', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '0612345678', 'Emic', 'ema@gmail.com');
INSERT INTO public.users (gender, role, address, city, country, jmbg, name, password, phone_number, surname, username) VALUES (0, 0, 'Futoski put 56', 'Novi Sad', 'Srbija', '2609992456789', 'Milos', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '064566789', 'Milosevic', 'milos@gmail.com');

INSERT INTO public.users (gender, role, address, city, country, jmbg, name, password, phone_number, surname, username) VALUES (0, 0, 'Zmaj Jovina 23', 'Beograd', 'Srbija', '1010982098009', 'Petar', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '064345667', 'Petrovic', 'petar@gmail.com');
INSERT INTO public.users (gender, role, address, city, country, jmbg, name, password, phone_number, surname, username) VALUES (1, 0, 'Ive Andrica 55', 'Beograd', 'Srbija', '1105990765234', 'Mila', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '0625456544', 'Milic', 'mila@gmail.com');

INSERT INTO public.users (gender, role, address, city, country, jmbg, name, password, phone_number, surname, username) VALUES (0, 0, 'Bulevar Evrope 42', 'Nis', 'Srbija', '2107991234567', 'Nemanja', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '061567890', 'Nemanjic', 'nemanja@gmail.com');
INSERT INTO public.users (gender, role, address, city, country, jmbg, name, password, phone_number, surname, username) VALUES (1, 0, 'Bulevar oslobodjenja 52', 'Nis', 'Srbija', '1203986345009', 'Kristina', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '064567892', 'Krstic', 'kristina@gmail.com');

INSERT INTO public.users (gender, role, address, city, country, jmbg, name, password, phone_number, surname, username) VALUES (0, 0, 'Bulevar Patrijarha Pavla 19', 'Sombor', 'Srbija', '1109992345678', 'Bojan', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '06109028349', 'Bojic', 'bojan@gmail.com');
INSERT INTO public.users (gender, role, address, city, country, jmbg, name, password, phone_number, surname, username) VALUES (1, 0, 'Balzakova 33', 'Sombor', 'Srbija', '1006999123456', 'Sanja', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '0640389840', 'Sanjic', 'sanja@gmail.com');
INSERT INTO public.users (gender, role, address, city, country, jmbg, name, password, phone_number, surname, username) VALUES (0, 0, 'Zlatne grede 22', 'Sombor', 'Srbija', '0807994345678', 'Uroš', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '062664647', 'Urošević', 'uros@gmail.com');


INSERT INTO public.users (gender, role, address, city, country, jmbg, name, password, phone_number, surname, username) VALUES (0, 0, 'Dinarska 78', 'Kragujevac', 'Srbija', '0908993456789', 'Dejan', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '0618298445', 'Dejic', 'dejan@gmail.com');
INSERT INTO public.users (gender, role, address, city, country, jmbg, name, password, phone_number, surname, username) VALUES (1, 0, 'Dalmatinska 52', 'Kragujevac', 'Srbija', '3011982345098', 'Dejana', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '0647324847', 'Dejic', 'dejana@gmail.com');

INSERT INTO public.users (gender, role, address, city, country, name, password, phone_number, surname, username) VALUES (1, 2, 'Marka Miljanova 11', 'Novi Sad', 'Srbija',  'Nikolina', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '062134567', 'Nikic', 'nina@gmail.com');
INSERT INTO public.users (gender, role, address, city, country, name, password, phone_number, surname, username) VALUES (0, 2, 'Narodnih heroja 21', 'Beograd', 'Srbija',  'Bojan', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '062743443', 'Bojanic', 'boki@gmail.com');
INSERT INTO public.users (gender, role, address, city, country, name, password, phone_number, surname, username) VALUES (1, 2, 'Majke Jugovica 45', 'Nis', 'Srbija',  'Dajana', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '062134567', 'Dakic', 'dajana@gmail.com');
INSERT INTO public.users (gender, role, address, city, country, name, password, phone_number, surname, username) VALUES (0, 2, 'Otona Zupancica 22', 'Sombor', 'Srbija',  'Srdjan', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '0684958956', 'Simic', 'srdjan@gmail.com');
INSERT INTO public.users (gender, role, address, city, country, name, password, phone_number, surname, username) VALUES (1, 2, 'Tekelijina 44', 'Kragujevac', 'Srbija',  'Danijela', '$2a$10$MoN4ofzCPOulneFJZFNEROhIbw3xjdx7lJFBpTsCxu.je1hF2oJGy', '062354561', 'Danicic', 'danijela@gmail.com');


INSERT INTO public.blood_center (capacity, working_time_from, working_time_to, manager_id, description, address, city, country, email, name, phone_number) VALUES (5, 7, 19, 15, 'Zavod za transfuziju krvi Vojvodine je visokospecijalizovana zdravstvena ustanova koja više od šest decenija vrši prikupljanje, čuvanje, testiranje i pripremu produkata od krvi kao i izvođenje laboratorijskih analiza potrebnih za uspješnu i sigurnu primjenu transfuzije krvi. Prikupljanje potrebnih količina krvi i produkata od krvi za liječenje povrijeđenih i oboljelih lica odvija se uz nesebičnu saradnju humanih građana na teritoriji Novog Sada, Južno bačkog-okruga i drugih dijelova Vojvodine. Stalna aktivnost Zavoda na razvoju kvaliteta usluga i proizvoda zasnovana je na najnovijim naučnim dostignućima, unapređenju postojećih i uvođenju novih savremenih metodologija rada. Nastavnom i naučnom djelatnošću u oblasti transfuziologije Zavod prenosi svoje znanje i stečeno iskustvo studentima i specijalizantima, vrši edukaciju zaposlenih.', 'Futoški put 11', 'Novi Sad', 'Srbija', 'institutV@gmail.com', 'Institut za dobrovoljno davanje krvi Vojvodine', '0214877999');
INSERT INTO public.blood_center (capacity, working_time_from, working_time_to, manager_id, description, address, city, country, email, name, phone_number) VALUES (10, 8, 20, 16, 'Misija Instituta za transfuziju krvi Beograd je da realizuje aktivnosti na omasovljenju davalaštva krvi; promoviše dobrovoljno, anonimno i nenagrađeno davalaštvo krvi; obezbjeđuje dovoljne količine sigurne krvi i produkata od krvi za potrebe liječenja građana, pruža laboratorijske i terapijske zdravstvene usluge usaglašene sa zahtjevima, potrebama i očekivanjima korisnika, edukuje transfuziologe i transfuziste za potrebe cijele naše zemlje.', 'Omladinska 52', 'Beograd', 'Srbija', 'institutB@gmail.com', 'Institut za dobrovoljno davanje krvi Beograd', '0113812712');
INSERT INTO public.blood_center (capacity, working_time_from, working_time_to, manager_id, description, address, city, country, email, name, phone_number) VALUES (6, 7, 20, 17, 'Prije 75 godine formirana je služba za transfuziju krvi u Nišu koja je na svom razvojnom putu prošla kroz više faza, od kojih je svaka ostavila tragove na njenu sadašnju fizionomiju. Rad Zavoda za transfuziju krvi Niš karakteriše kontinuitet u svim djelatnostima uz intenzivno osavremenjivanje rada. Obezbjedjivanje potrebnih količina krvi može se postići samo djelatnošću dobro organizovane, medjusobno uskladjene i savremeno postavljene službe za transfuziju krvi koja kao takva, u cjelini dobija realnu mogućnost da odgovori zadacima koji joj se postavljaju, što su sve karakteristike Zavoda za transfuziju krvi Niš. Zahvaljujući ovakvim karakteristikama, Zavod za transfuziju krvi Niš stiče uslove da prati i primjenjuje sva savremena dostignuća u svjetskoj transfuziologiji, a to znači da se pacijentu obezbjedjuje sve ono što je medicinski, etički i ekonomski najcjelishodnije.', 'Jevrejska 33', 'Niš', 'Srbija', 'institutN@gmail.com', 'Institut za dobrovoljno davanje krvi Niš', '0184533106');
INSERT INTO public.blood_center (capacity, working_time_from, working_time_to, manager_id, description, address, city, country, email, name, phone_number) VALUES (3, 9, 20, 18, 'Stručni rad Zavoda za transfuziju krvi Sombor je pod stalnom kontrolom direktora, načelnika odjeljenja i ostalih ljekara, što dovodi do visokostručnog rada, a sve usled toga što Somborski Zavod ima vrhunske stručnjake u svim oblastima transfuzije. Zavod intenzivno radi na omasovljavanju dobrovoljnog davalaštva krvi, separiranju krvi, uvodjenju novih analiza koje daju sigurnost primjene krvi i krvnih derivata, uvodjenju novih tehnologija u svim oblastima, prenatalnoj zaštiti, HLA tipizaciji, terapijskoj i donorskoj plazmaferezi i citoferezi, ambulantnim i kućnim transfuzijama, kompjuterizaciji procesa rada, uključujući i rad zajedničkih službi, edukaciju svih profila medicinskih radnika i praćenje i učestvovanje u naučno istraživačkim radovima. Danas je Zavod za transfuziju krvi visokostručna, specijalizovana, savremena institucija.', 'Marije Kiri 19', 'Sombor', 'Srbija', 'institutS@gmail.com', 'Institut za dobrovoljno davanje krvi Sombor', '025468111');
INSERT INTO public.blood_center (capacity, working_time_from, working_time_to, manager_id, description, address, city, country, email, name, phone_number) VALUES (7, 7, 18, 19, 'Misija Crvenog krsta Kragujevca je da olakšava ljudsku patnju, sa zadacima: da pruža pomoć ugroženim licima u slučaju ratnih sukoba, prirodnih, ekoloških ili drugih nesreća, spasava ugrožene živote i zdravlje ljudi i širi znanja o međunarodnom humanitarnom pravu, da preventivno djeluje i prosvjećuje građane u oblasti zdravstvene i socijalne zaštite i unaprijeđuje humanitarne vrijednosti u društvu i, u slučaju stanja potreba, pruža socijalnu zaštitu i zbrinjavanje. U ostvarivanju navedenih ciljeva i zadataka, Crveni krst Kragujevca pomaže svim ljudima, bez bilo kakve neposredne ili posredne diskriminacije po bilo kom osnovu, a naročito zbog rase, boje, pola, nacionalne pripadnosti, društvenog porijekla, rođenja ili sličnog statusa, vjeroispovesti, političkog ili drugog uvjerenja, imovnog stanja, kulture, jezika, starosti ili psihičkog ili fizičkog invaliditeta.', 'Svetozara Markovića 7', 'Kragujevac', 'Srbija', 'institutK@gmail.com', 'Crveni krst Kragujevac', '034332617');


INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 2, 2, '20210317 09:00:00 AM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 2, '20211011 10:00:00 AM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 2, '20220315 09:00:00 AM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 2, '20220726 08:00:00 AM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 2, '20221110 05:00:00 PM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 2, '20230419 06:00:00 PM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 2, '20231120 08:00:00 AM');



INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 3, '20201112 06:00:00 PM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 3, '20210203 09:00:00 AM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 3, '20220315 09:00:00 AM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 3, '20220624 09:00:00 AM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 3, '20230125 09:00:00 AM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 3, '20231114 08:00:00 AM');


INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 4, '20230125 09:00:00 AM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 1, 4, '20230725 08:00:00 AM');


INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 4, 10, '20231114 10:00:00 AM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 4, 11, '20231114 10:00:00 AM');
INSERT INTO public.appointment (canceled, center_id, donor_id, start_date_time) VALUES (false, 4, 12, '20231114 10:00:00 AM');


